### ISSUE TITLE
Want to move operation to build development environment to `petit-proj-api:dev` image

### ISSUE THREAD

**Issue by dzeyelid** [lefthandz-dev/petit-projects#9]
Currently, I do the operation in docker-compose.dev.yml. ([refs](https://github.com/lefthandz-dev/petit-projects/blob/develop/docker-compose.dev.yml#L3-L9))

```yml
  api:
    build: apps/api
    image: petit-proj-api
    volumes:
      - ./apps/api/app:/var/www/html
      - ./apps/api/ops/docker/run-dev.sh:/usr/local/run-dev.sh
    command: ["sh", "/usr/local/run-dev.sh"]
```

But I want to move that into `petit-proj-api:dev` image.

Probably I may need a registry to keep it in.
